# This config file for Travis CI utilizes ros-industrial/industrial_ci package.		
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst		
sudo: required 		
dist: trusty 		
services:		
  - docker		
language: generic 		
compiler:		
  - gcc		
notifications:		
  email:
    on_success: never
    on_failue: never
  slack: ouxt-polaris-2018:NclavkPPXCVkysAoOTr47aUg
env:		
  global:		
    - CATKIN_PARALLEL_TEST_JOBS=-p1
    - ROS_PARALLEL_TEST_JOBS=-j`nproc`
    
  matrix:		
    - ROS_DISTRO=kinetic ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
before_install:
    - "easy_install --version"
    - "pip freeze"
    - "travis_retry pip install -U setuptools"
    - "cd `mktemp -d`"
    - "travis_retry wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py"
    - "travis_retry python get-pip.py"
    - "cd $OLDPWD"
    - "pip --version"
    - "easy_install --version"
install:		
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config		
  - pip install overpy
script:		
  - source .ci_config/travis.sh 
git:
  submodules: true
