# This config file for Travis CI utilizes ros-industrial/industrial_ci package.		
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst		
sudo: required 		
dist: trusty 		
services:		
  - docker		
language: generic 		
compiler:		
  - gcc		
notifications:		
  email:
    on_success: never
    on_failue: never
  slack: ouxt-polaris-2018:NclavkPPXCVkysAoOTr47aUg
env:		
  global:		
    - CATKIN_PARALLEL_TEST_JOBS=-p1
    - ROS_PARALLEL_TEST_JOBS=-j`nproc`
    
  matrix:		
    - ROS_DISTRO=kinetic ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
install:		
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config		
  - sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
  - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.2.88-1_amd64.deb
  - sudo dpkg -i cuda-repo-ubuntu1604_9.2.88-1_amd64.deb
  - rm cuda-repo-ubuntu1604_9.2.88-1_amd64.deb
  - sudo apt update
  - sudo apt install -y aptitude
  - sudo aptitude install -y cuda
  - export PATH="/usr/local/cuda/bin:$PATH"
  - export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
script:		
  - source .ci_config/travis.sh 
git:
  submodules: true
