input_cloud: /pointcloud_merger_node/merged_points
# CONDITIONAL_EUCLIDIAN_CLUSTERING = 0
# EUCLIDIAN_CLUSTER_EXTRACTION = 1
clustering_method: 1

downsample:
  enable: false

conditional_euclidean_clustering:
  min_cluster_size: 3
  max_cluster_size: 300
  radius_search: 0.1
  cluster_tolerance: 500

min_bbox_size: 0
max_bbox_size: 3