right_image_topic: /wam_v/right_camera/right_image_raw
right_camera_info_topic: /wam_v/right_camera/right_camera_info
left_image_topic: /wam_v/left_camera/left_image_raw
left_camera_info_topic: /wam_v/left_camera/left_camera_info
euclidean_cluster_topic: /euclidean_clustering_node/bbox
publish_disparity: true