mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: localhost # set MQTT Server IP or URL
    port: 1883
    keepalive: 60
  private_path: device/001
selializer: msgpack:dumps
deselializer: msgpack:loads
bridge:
  # diagnostic_agg
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: diagnostic_msgs.msg:DiagnosticArray
    topic_from: /diagnostics_agg
    topic_to: diagnostics_agg
  # heartbeat
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: robotx_msgs.msg:Heartbeat
    topic_from: /heartbeat
    topic_to: heartbeat
  # object recognition
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: robotx_msgs.msg:ObjectRegionOfInterestArray
    topic_from: /cnn_prediction_node/object_roi
    topic_to: objects