# Default parameters used by the yocs_velocity_smoother module.
# This isn't used by minimal.launch per se, rather by everything
# which runs on top.

# Mandatory parameters
speed_lim_v: 0.5
speed_lim_w: 0.2

accel_lim_v: 0.1 # maximum is actually 2.0, but we push it down to be smooth
accel_lim_w: 0.1

# Optional parameters
frequency: 10.0
decel_factor: 1.5

# Robot velocity feedback type:
#  0 - none (default)
#  1 - odometry
#  2 - end robot commands
robot_feedback: 2