# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50    
# Position Controllers ---------------------------------------
left_thruster_position_controller:
  type: position_controllers/JointPositionController
  joint: left_thruster_joint
  pid: {p: 100, i: 10, d: 0, i_clamp: 100}
right_thruster_position_controller:
  type: position_controllers/JointPositionController
  joint: right_thruster_joint
  pid: {p: 100, i: 10, d: 0, i_clamp: 100}
