analyzers:
  computers:
    type: diagnostic_aggregator/GenericAnalyzer
    path: gpu_device
    find_and_remove_prefix: "cuda_diagnostic_node:"
  tf:
    type: diagnostic_aggregator/GenericAnalyzer
    path: TF
    find_and_remove_prefix: "tf_monitor:"
  joy:
    type: diagnostic_aggregator/GenericAnalyzer
    path: joy
    find_and_remove_prefix: "joy_node:"
  thruster:
    type: diagnostic_aggregator/GenericAnalyzer
    path: thruster
    find_and_remove_prefix: "robotx_hardware_interface_node:"